config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :recipes, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def new
    @recipe = Recipe.new
  end

  def create
    Recipe.create(params.require(:recipe)
                        .permit(:title, :cook_time, :cook_method, 
                                :ingredients, :recipe_type, :cuisine))
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Boas vindas ao CookBook um site de receitas legais</h1>

<%= link_to 'Cadastrar receita', new_recipe_path %>

<% @recipes.each do |recipe| %>
  <h3><%= recipe.title %></h3>
  <dl>
    <dt>Cozinha</dt>
    <dd><%= recipe.cuisine %></dd>
    <dt>Tipo</dt>
    <dd><%= recipe.recipe_type %></dd>
    <dt>Tempo de preparo</dt>
    <dd><%= recipe.cook_time %> minuto(s)</dd>
  </dl>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/new.html.erb
<%= form_with model: @recipe, local: true do |f| %>
  <div>
    <%= f.label :title, 'Título' %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :cuisine, 'Cozinha' %>
    <%= f.text_field :cuisine %>
  </div>
  <div>
    <%= f.label :recipe_type, 'Tipo' %>
    <%= f.text_field :recipe_type %>
  </div>
  <div>
    <%= f.label :cook_time, 'Tempo de preparo' %>
    <%= f.number_field :cook_time %>
  </div>
  <div>
    <%= f.label :ingredients, 'Ingredientes' %>
    <%= f.text_field :ingredients %>
  </div>
  <div>
    <%= f.label :cook_method, 'Modo de preparo' %>
    <%= f.text_area :cook_method %>
  </div>
  <%= f.submit 'Cadastrar' %>
<% end %>